window.ARVI_LINKS = {
  profile: {
    kicker: 'IA + automatización + formación',
    title: 'Todo Arvi, en un solo lugar.',
    description: 'Automatizamos tareas, construimos agentes de inteligencia artificial y enseñamos a usar la tecnología sin enredos.',
  },
  featured: {
    id: 'masterclass-emprendedoras',
    eyebrow: 'Preinscripciones abiertas',
    title: 'IA para Mujeres Emprendedoras',
    description: 'Una masterclass práctica para crear contenido, organizar tu negocio y recuperar tiempo usando inteligencia artificial.',
    meta: 'Virtual · Gratuita · Incluye kit práctico',
    href: 'https://emprendedoras.academy.arvi.rohigroup.co',
    external: true,
  },
  links: [
    {
      id: 'whatsapp-automatizacion',
      icon: 'sparkles',
      title: 'Quiero automatizar mi negocio',
      description: 'Cuéntanos qué tarea te quita tiempo y revisamos cómo Arvi puede ayudarte.',
      href: 'https://wa.me/573183074381?text=Hola%2C%20quiero%20conocer%20c%C3%B3mo%20Arvi%20puede%20automatizar%20mi%20negocio.',
      external: true,
      tone: 'primary',
      eyebrow: 'Hablemos de tu negocio',
    },
    {
      id: 'arvi-agente',
      icon: 'bot',
      title: 'Conoce Arvi Agente IA',
      description: 'Atiende clientes, organiza conversaciones y apoya tu operación por WhatsApp.',
      href: '/agente',
      external: false,
      tone: 'green',
      eyebrow: 'Tu equipo digital',
    },
    {
      id: 'arvi-academy',
      icon: 'academy',
      title: 'Explora Arvi Academy',
      description: 'Capacitaciones para aplicar la inteligencia artificial al trabajo y al negocio real.',
      href: 'https://academy.arvi.rohigroup.co',
      external: true,
      tone: 'violet',
      eyebrow: 'Aprende y aplica',
    },
    {
      id: 'nomina',
      icon: 'payroll',
      title: 'IA para Nómina y Seguridad Social',
      description: 'Ruta práctica para profesionales que quieren trabajar más rápido sin perder el control.',
      href: 'https://nomina.academy.arvi.rohigroup.co',
      external: true,
      tone: 'soft',
      eyebrow: 'En preparación',
    },
    {
      id: 'empresas',
      icon: 'teams',
      title: 'Capacitaciones para empresas y equipos',
      description: 'Diseñamos talleres ajustados a los procesos y retos de tu organización.',
      href: 'mailto:rohigroupsas@gmail.com?subject=Capacitaci%C3%B3n%20para%20mi%20equipo%20con%20Arvi',
      external: true,
      tone: 'soft',
      eyebrow: 'Programas personalizados',
    },
  ],
  footer: [
    {
      id: 'whatsapp',
      label: 'WhatsApp',
      href: 'https://wa.me/573183074381',
      external: true,
    },
    {
      id: 'correo',
      label: 'Correo',
      href: 'mailto:rohigroupsas@gmail.com',
      external: true,
    },
    {
      id: 'rohi-group',
      label: 'Rohi Group',
      href: 'https://rohigroup.co',
      external: true,
    },
  ],
};
